---
- name: create ald domain server
  hosts: dc
  become: yes

  vars:
    kerb_admin_pass: 12345678
    ald_admin_pass: 12345678
    user_pass: 12345678
    packages:
      - apache2
      - libapache2-mod-auth-kerb
      - php7.0
      - php7.0-curl 
      - php7.0-gd 
      - php7.0-pgsql 
      - php7.0-xmlrpc 
      - php7.0-xsl 
      - php7.0-imagick 
      - php7.0-intl
    path_to_www: /DATA/www 

  tasks:
    - name: install packages
      apt:
        name: '{{ item }}'
      loop: 
          - '{{ packages }}'
    - name: Enable modules
      apache2_module:
        state: present
        name: '{{ item }}'
        with_item:
          - auth_kerb
          - rewrite
    - name: Create www directory
      file:
        path: '{{ path_to_www }}'
        state: directory
    - name: Create site conf file
      template:
        src: templates/site.conf.j2
        dest: /etc/apache2/site-available/000-default.conf
    - name: Create passfile
      copy:
        content: |
                  K/M:12345678
                  admin/admin:12345678
                  default/user:12345678
        dest: /opt/passfile
        mode: 0400


    - name: Create keytab apache2
      shell: "ald-client update-svc-keytab HTTP/{{ ansible_fqdn }} --ktfile=/etc/apache2/keytab -f --pass-file=/opt/passfile && chmod 644 /etc/apache2/keytab && chown www-data /etc/apache2/keytab"
    - debug: msg="Создайте принципала в домене HTTP/{{ ansible_fqdn }}"




    - name: Generate passfile
      copy:
        content: |
                  K/M:{{ kerb_admin_pass }}
                  admin/admin:{{ ald_admin_pass }}
                  default/user: {{ user_pass }}
        dest: /opt/passfile
        owner: root
        group: root
        mode: 0400


  handlers:
  - name: Restart bind9
    service: name=bind9 state=restarted 
  - name: Restart ntp
    service: name=ntp state=restarted
