---
# tasks file for ald-dc
    - name: edit ald conf
      template:
        src: ald.conf.j2
        dest: /etc/ald/ald.conf
    - name: Generate passfile
      copy:
        content: |
                  K/M:{{ kerb_admin_pass }}
                  admin/admin:{{ ald_admin_pass }}
                  default/user: {{ user_pass }}
        dest: /opt/passfile
        owner: root
        group: root
        mode: 0400
    - name: init ald dc
      shell: "ald-init init -f --pass-file /opt/passfile && rm -r /opt/passfile"